const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS', 
    USER_LOGIN_FAIL:'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',



    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILD:'CREATE_USER_FAILD',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILD:'EDIT_USER_FAILD',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILD:'DELETE_USER_FAILD',

    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',

    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',
    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',

    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS', 

    FETCH_ALL_SPECIALTY_FAILED: 'FETCH_ALL_SPECIALTY_FAILED',
    FETCH_ALL_SPECIALTY_SUCCESS: 'FETCH_ALL_SPECIALTY_SUCCESS',

    FETCH_ALL_EXAMINATION_FAILED: 'FETCH_ALL_EXAMINATION_FAILED',
    FETCH_ALL_EXAMINATION_SUCCESS: 'FETCH_ALL_EXAMINATION_SUCCESS',

    SAVE_DETAIL_DOCTOR_FAILED: 'SAVE_DETAIL_DOCTOR_FAILED',
    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',

    FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS:'FETCH_ALLCODE_SCHEDULE_HOURS_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_HOURS_FAILED:'FETCH_ALLCODE_SCHEDULE_HOURS_FAILED',

    FETCH_ALL_DAY_DOCTOR_SUCCESS:'FETCH_ALL_DAY_DOCTOR_SUCCESS',
    FETCH_ALL_DAY_DOCTOR_FAILED:'FETCH_ALL_DAY_DOCTOR_FAILED',


    
    FETCH_ALL_DAY_SUCCESS:'FETCH_ALL_DAY_SUCCESS',
    FETCH_ALL_DAY_FAILED:'FETCH_ALL_DAY_FAILED',


    FETCH_ALL_SLOTTIME_SUCCESS:'FETCH_ALL_SLOTTIME_SUCCESS',
    FETCH_ALL_SLOTTIME_FAILED:'FETCH_ALL_SLOTTIME_FAILED',


    FETCH_ALL_PAYMENT_SUCCESS:'FETCH_ALL_PAYMENT_SUCCESS',
    FETCH_ALL_PAYMENT_FAILED:'FETCH_ALL_PAYMENT_FAILED',

})

export default actionTypes;